site_name: Tanaguru Jenkins plugin
pages:
- ['index.md', 'Home']
- ['network-architecture.md', 'Network Architecture']
- ['install-doc.md', 'Installation']
- ['configuration.md', 'Configuration']
- ['graphs.md', 'Graphs creation and customisation']
- ['developer-doc.md', 'Developer doc']

theme: readthedocs
repo_url: https://github.com/Tanaguru/jenkins-tanaguru-plugin
